# Generated by Django 4.0.2 on 2022-04-06 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0018_delete_classschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsUnderStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.classlist')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentdetails')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacherbasic')),
            ],
            options={
                'db_table': 'studentsunderme',
            },
        ),
    ]
