# Generated by Django 4.0.2 on 2022-03-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.DateField()),
            ],
            options={
                'db_table': 'adminlogin',
            },
        ),
        migrations.CreateModel(
            name='TeacherBasic',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_profile', models.ImageField(upload_to='teachers/')),
                ('t_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=7)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('religion', models.CharField(max_length=15)),
                ('cast', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=20)),
                ('district', models.CharField(default='', max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('aadhar_num', models.IntegerField()),
                ('email_id', models.CharField(max_length=25)),
                ('phone_number', models.IntegerField()),
                ('handling_class', models.IntegerField()),
                ('subject', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=50)),
                ('quali_certificate', models.FileField(upload_to='teachers/')),
                ('instituation_name', models.CharField(max_length=50)),
                ('year_of_experience', models.IntegerField()),
                ('experience_certificate', models.FileField(upload_to='teachers/')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
