# Generated by Django 4.0.2 on 2022-03-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_profile', models.ImageField(upload_to='students/')),
                ('s_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=7)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('religion', models.CharField(max_length=15)),
                ('cast', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('aadhar_num', models.IntegerField()),
                ('email_id', models.CharField(max_length=25)),
                ('phone_number', models.IntegerField()),
                ('registration_num', models.IntegerField()),
                ('classs', models.IntegerField()),
                ('division', models.CharField(max_length=1)),
                ('father_name', models.CharField(max_length=20)),
                ('father_occupation', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('mother_occupation', models.CharField(max_length=20)),
                ('parents_phone', models.IntegerField()),
                ('parents_email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
