# Generated by Django 4.0.2 on 2022-03-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_classlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
