# Generated by Django 4.0.2 on 2022-03-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_classlist_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlist',
            name='teacher',
        ),
    ]
