# Generated by Django 4.0.2 on 2022-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_classlist_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherbasic',
            name='division',
            field=models.CharField(default='', max_length=2),
        ),
    ]
