# Generated by Django 4.0.2 on 2022-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_teacherbasic_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherbasic',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='teacherbasic',
            name='quali_certificate',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='teachers/'),
        ),
    ]
