# Generated by Django 4.0.2 on 2022-03-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_teacherbasic_experience_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherbasic',
            name='aadhar_num',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teacherbasic',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
