# Generated by Django 4.0.2 on 2022-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_teacherbasic_experience_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherbasic',
            name='instituation_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacherbasic',
            name='year_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
