# Generated by Django 4.0.2 on 2022-03-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_teacherbasic_instituation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
