# Generated by Django 4.0.2 on 2022-03-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_studentdetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='aadhar_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='parents_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
