# Generated by Django 4.0.2 on 2022-03-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_classschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
    ]
