# Generated by Django 4.0.2 on 2022-04-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_alter_admindetails_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherbasic',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='teacherbasic',
            name='religion',
        ),
    ]
