# Generated by Django 4.0.2 on 2022-04-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_teacherbasic_cast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='religion',
        ),
    ]
