# Generated by Django 4.0.2 on 2022-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_remove_studentdetails_cast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='registration_num',
            field=models.CharField(max_length=50),
        ),
    ]
