# Generated by Django 4.0.2 on 2022-04-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_delete_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='classes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.classlist'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.classlist')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacherbasic')),
            ],
            options={
                'db_table': 'scheduledclass',
            },
        ),
    ]
