# Generated by Django 4.0.2 on 2022-04-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_remove_studentdetails_classs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='classs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='division',
            field=models.CharField(default='', max_length=1),
        ),
    ]
