# Generated by Django 4.0.2 on 2022-04-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_alter_studentdetails_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='classes',
        ),
    ]
