# Generated by Django 4.0.2 on 2022-04-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_remove_teacherbasic_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlist',
            old_name='c_id',
            new_name='id',
        ),
    ]
