# Generated by Django 4.0.2 on 2022-04-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_rename_id_classlist_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='division',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='classes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.classlist'),
        ),
    ]
